site_name: Copper
repo_url: https://github.com/LeoRiether/Copper/
site_url: https://leoriether.github.io/Copper/
theme:
  name: material # https://github.com/squidfunk/mkdocs-material
  palette:
    scheme: slate
    primary: deep orange
    accent: pink
extra_css: [extra/extra.css]
extra_javascript:
  - extra/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
