name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: abel0b/setup-premake@v2.3
      with:
        version: "5.0.0-beta2"
    - name: premake
      run: premake5 gmake2
    - name: make
      run: make
